services:

  account-service:
    build:
      context: ./AccountService
      dockerfile: Dockerfile-account
    ports:
      - 9090:8080
  transaction-service:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile-transaction
    ports:
      - 9091:8080
