FROM eclipse-temurin:21


# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8091 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=TransactionService/target/bank-transaction-service.jar

# Add the application's jar to the container
ADD ${JAR_FILE} bank-transaction-service.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/bank-transaction-service.jar"]